server:
  port: 8080  # 애플리케이션이 실행될 포트

spring:
  mvc:
    view:
      prefix: /WEB-INF/jblog/
      suffix: .jsp

  main:
    banner-mode: off

  logging:
    level:
      root: DEBUG

  datasource:
    url: jdbc:h2:tcp://localhost/~/test  # H2 서버 모드 URL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: true  # 데이터베이스 연결을 컨트롤러 객체까지 유지시킬 수 있다.
    show-sql: true  # SQL 쿼리 로그 출력
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # H2 Dialect 설정

  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mybatis-config.xml